# Generated by Django 6.0 on 2026-02-17 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductivityInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('trend', 'Productivity Trend'), ('pattern', 'Behavioral Pattern'), ('recommendation', 'Improvement Recommendation'), ('achievement', 'Achievement Unlocked'), ('warning', 'Performance Warning'), ('prediction', 'Future Prediction')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('data_points', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_actionable', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Productivity Insight',
                'verbose_name_plural': 'Productivity Insights',
                'db_table': 'productivity_insights',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('overdue_tasks', models.PositiveIntegerField(default=0)),
                ('cancelled_tasks', models.PositiveIntegerField(default=0)),
                ('total_time_spent', models.PositiveIntegerField(default=0)),
                ('average_completion_time', models.FloatField(default=0.0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('on_time_rate', models.FloatField(default=0.0)),
                ('efficiency_score', models.FloatField(default=0.0)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task Analytics',
                'verbose_name_plural': 'Task Analytics',
                'db_table': 'task_analytics',
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productivity_score', models.FloatField(default=0.0)),
                ('efficiency_rating', models.CharField(default='average', max_length=20)),
                ('average_daily_tasks', models.FloatField(default=0.0)),
                ('completion_rate_7d', models.FloatField(default=0.0)),
                ('completion_rate_30d', models.FloatField(default=0.0)),
                ('completion_rate_overall', models.FloatField(default=0.0)),
                ('most_productive_hour', models.IntegerField(blank=True, null=True)),
                ('least_productive_hour', models.IntegerField(blank=True, null=True)),
                ('average_task_duration', models.FloatField(default=0.0)),
                ('current_streak_days', models.PositiveIntegerField(default=0)),
                ('longest_streak_days', models.PositiveIntegerField(default=0)),
                ('consistency_score', models.FloatField(default=0.0)),
                ('preferred_category_id', models.IntegerField(blank=True, null=True)),
                ('category_distribution', models.JSONField(default=dict)),
                ('predicted_completion_probability', models.FloatField(default=0.5)),
                ('suggested_daily_task_limit', models.PositiveIntegerField(default=5)),
                ('optimal_scheduling_pattern', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_calculated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'User Analytics',
                'verbose_name_plural': 'User Analytics',
                'db_table': 'user_analytics',
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('total_time_logged', models.PositiveIntegerField(default=0)),
                ('most_productive_day', models.CharField(blank=True, max_length=10)),
                ('category_stats', models.JSONField(default=dict)),
                ('achievements_unlocked', models.JSONField(default=list)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('key_insights', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Weekly Report',
                'verbose_name_plural': 'Weekly Reports',
                'db_table': 'weekly_reports',
                'ordering': ['-week_start'],
            },
        ),
    ]
