# Generated by Django 6.0 on 2026-02-17 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productivityinsight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskanalytics',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='categories.category'),
        ),
        migrations.AddField(
            model_name='taskanalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useranalytics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='productivityinsight',
            index=models.Index(fields=['user', 'insight_type'], name='productivit_user_id_61b466_idx'),
        ),
        migrations.AddIndex(
            model_name='productivityinsight',
            index=models.Index(fields=['generated_at'], name='productivit_generat_ddaad3_idx'),
        ),
        migrations.AddIndex(
            model_name='taskanalytics',
            index=models.Index(fields=['user', 'start_date', 'end_date'], name='task_analyt_user_id_25ff15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskanalytics',
            unique_together={('user', 'category', 'start_date', 'end_date')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together={('user', 'week_start')},
        ),
    ]
