org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=C:\\Users\\LOQ\\Downloads\\java-17-openjdk-17.0.18.0.8-1.win.jdk.x86_64\\java-17-openjdk-17.0.18.0.8-1.win.jdk.x86_64