# Generated by Django 6.0 on 2026-02-17 08:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(choices=[(1, 'Work'), (2, 'Personal'), (3, 'Health'), (4, 'Learning'), (5, 'Finance'), (6, 'Social'), (7, 'Home')], primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
                ('icon', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('pending_tasks', models.IntegerField(default=0)),
                ('overdue_tasks', models.IntegerField(default=0)),
                ('total_time_spent', models.DurationField(default=datetime.timedelta)),
                ('average_completion_time', models.DurationField(blank=True, null=True)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('on_time_completion_rate', models.FloatField(default=0.0)),
                ('total_points_earned', models.IntegerField(default=0)),
                ('first_task_created', models.DateTimeField(blank=True, null=True)),
                ('last_task_completed', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='categories.category')),
            ],
            options={
                'verbose_name': 'Category Statistics',
                'verbose_name_plural': 'Category Statistics',
                'db_table': 'category_stats',
            },
        ),
    ]
