# Generated by Django 6.0 on 2026-02-17 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categorystats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='categorystats',
            index=models.Index(fields=['user', 'category'], name='category_st_user_id_7c4ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='categorystats',
            index=models.Index(fields=['completion_rate'], name='category_st_complet_802d80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categorystats',
            unique_together={('user', 'category')},
        ),
    ]
