// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBptnzJvJ4VTkie7rxOysG1lIyG0irhr_Y',
    appId: '1:325158322063:web:412b134b0f30839b8a55fa',
    messagingSenderId: '325158322063',
    projectId: 'taskcue-f2192',
    authDomain: 'taskcue-f2192.firebaseapp.com',
    storageBucket: 'taskcue-f2192.firebasestorage.app',
    measurementId: 'G-HHX82KR2YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD362lG6pDWmbWuEwQASLOTQBN_zXfY0e4',
    appId: '1:325158322063:android:c0880fe1137160368a55fa',
    messagingSenderId: '325158322063',
    projectId: 'taskcue-f2192',
    storageBucket: 'taskcue-f2192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe2D32v8fTtRTIcTdcQkCw7CsU2C4H-0w',
    appId: '1:325158322063:ios:efd9048fc988f9968a55fa',
    messagingSenderId: '325158322063',
    projectId: 'taskcue-f2192',
    storageBucket: 'taskcue-f2192.firebasestorage.app',
    iosBundleId: 'com.taskcue.taskcueApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBptnzJvJ4VTkie7rxOysG1lIyG0irhr_Y',
    appId: '1:325158322063:web:c03886acbd31332c8a55fa',
    messagingSenderId: '325158322063',
    projectId: 'taskcue-f2192',
    authDomain: 'taskcue-f2192.firebaseapp.com',
    storageBucket: 'taskcue-f2192.firebasestorage.app',
    measurementId: 'G-HXLQLBEL9E',
  );
}
