# Generated by Django 6.0 on 2026-02-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('task_milestone', 'Task Milestone'), ('streak_milestone', 'Streak Milestone'), ('level_up', 'Level Up'), ('category_expert', 'Category Expert'), ('time_management', 'Time Management'), ('consistency', 'Consistency'), ('special', 'Special Achievement')], max_length=20)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
                ('difficulty', models.CharField(default='easy', max_length=20)),
                ('points_reward', models.PositiveIntegerField(default=50)),
                ('requirements', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('earned', 'Points Earned'), ('bonus', 'Bonus Points'), ('penalty', 'Points Penalty'), ('reward', 'Reward Purchase'), ('gift', 'Gift Points')], max_length=20)),
                ('reason', models.CharField(max_length=255)),
                ('related_task_id', models.UUIDField(blank=True, null=True)),
                ('related_achievement_id', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Points Transaction',
                'verbose_name_plural': 'Points Transactions',
                'db_table': 'points_transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_type', models.CharField(choices=[('daily_tasks', 'Daily Task Completion'), ('weekly_goals', 'Weekly Goal Achievement'), ('category_focus', 'Category Focus Streak'), ('early_completion', 'Early Task Completion')], max_length=20)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('best_count', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('streak_start_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Streak',
                'verbose_name_plural': 'User Streaks',
                'db_table': 'user_streaks',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_data', models.JSONField(default=dict)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Achievement',
                'verbose_name_plural': 'User Achievements',
                'db_table': 'user_achievements',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('lifetime_points', models.PositiveIntegerField(default=0)),
                ('points_this_week', models.PositiveIntegerField(default=0)),
                ('points_this_month', models.PositiveIntegerField(default=0)),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('points_to_next_level', models.PositiveIntegerField(default=100)),
                ('last_weekly_reset', models.DateField(blank=True, null=True)),
                ('last_monthly_reset', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Points',
                'verbose_name_plural': 'User Points',
                'db_table': 'user_points',
            },
        ),
    ]
